name: Upload timing and validation results

on:
  push:
    branches:
      - DATA-566-view-timing-updates
      - main
  workflow_dispatch: {}

jobs:
  upload-results:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload timing-results.html artifact
        uses: actions/upload-artifact@v4
        with:
          name: timing-results
          path: timing-results.html

      - name: Upload validation-results.html artifact
        uses: actions/upload-artifact@v4
        with:
          name: validation-results
          path: validation-results.html

      - name: Upload index.html artifact
        uses: actions/upload-artifact@v4
        with:
          name: index
          path: index.html

